---
title: "Gráficos fictícios"
output: 
    html_document: 
        theme: paper 
        toc: true
        toc_depth: 2
        code_folding: hide
        toc_float: true
---

```{r setup, include = FALSE}
library(ggplot2)
```

# Plots
  
  Here I describe some codes to remember how I made the plots.

```{r}

#Data frame
df <- data.frame("atendimento" = c("Atendido", "Não Atendido", "Parcialmente
                                   Atendido"), 
                 "total_pedidos" = c(351,106,66),
                 "perc" = c("40 %", "12 %", "8 %"))

#Plot

mycols <- c("#ffa600", "#ff6361", "#bc5090", "#58508d")

ggplot(df, aes(x="", y=total_pedidos, fill=atendimento)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = total_pedidos, label = perc), color = "black", 
            position = position_stack(vjust = 0.6))+
  scale_fill_manual(values = mycols) +
  theme_void() +
  labs(fill = "Atendimento" , 
       title = "Atendimento a pedidos feitos à universidades e institutos federais")
```

# Agradecimentos

Agradeço blablablabla